# Test
sudo: enabled
dist: xenial
language: python
python: 3.7
git:
  depth: 1
install:
- wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
- sudo dpkg -i packages-microsoft-prod.deb
- sudo apt-get update
- sudo apt-get install dotnet-sdk-2.2
- dotnet tool install -g localappveyor --version 0.5.0-alpha.10
- PATH=$PATH:~/home/.dotnet/tools
- PATH=~/home/.dotnet/tools:$PATH
script:
- find $HOME/ -name 'LocalAppVeyor*'
- find $HOME/ -name 'localappveyor*'
# https://stackoverflow.com/a/105249/5951529
- cd $HOME/travis/.dotnet && ls -LR && tree -l
# which and whereis:
# https://superuser.com/a/461790/572069
- which LocalAppVeyor
- which localappveyor
- whereis LocalAppVeyor
- whereis localappveyor
# dpkg-query:
# https://superuser.com/a/173347/572069
- dpkg-query -L LocalAppVeyor
- dpkg-query -L localappveyor
- LocalAppVeyor lint --token $APPVEYOR_API_KEY
- localappveyor lint --token $APPVEYOR_API_KEY