# Test
sudo: enabled
dist: xenial
language: python
python: 3.7
git:
  depth: 1
install:
- wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
- sudo dpkg -i packages-microsoft-prod.deb
- sudo apt-get update
- sudo apt-get install dotnet-sdk-2.2
- dotnet tool install -g localappveyor --version 0.5.0-alpha.10
script:
- which LocalAppVeyor
- which localappveyor
- whereis LocalAppVeyor
- whereis localappveyor
- dpkg-query -L LocalAppveyor
- dpkg-query -L localappveyor
- LocalAppveyor lint --token $APPVEYOR_API_KEY
- localappveyor lint --token $APPVEYOR_API_KEY