before_install:
- pyenv global 3

before_script:
- cat /etc/os-release | grep "VERSION"
- python --version
- pipenv --version
# - node --version
# - which python
# - pip --version
# - .venv/bin/pip --version

cache:
  directories:
  - $HOME/.npm
  # - $HOME/.cache/pip

dist: noble

git:
  depth: 1

install:
- nvm install node
- npm install --global @choksheak/timecli
- python -m pip install --upgrade pip
- pip install pipenv
- timecli pipenv install --dev
- timecli pipenv install --dev hello-world
- timecli pipenv uninstall --dev hello-world
# - python -m venv .venv
# - .venv/bin/python -m pip install --upgrade pip
# - timecli ".venv/bin/pip" install --no-cache-dir --requirement requirements.txt
# - timecli ".venv/bin/pip" install hello-world --no-cache-dir
# - timecli ".venv/bin/pip" uninstall hello-world --no-cache-dir --yes

language: shell

os: linux

script: skip
