before_script:
- cat /etc/os-release | grep "VERSION"
- timecli --version
- python --version
- .venv/bin/pip --version

cache:
  directories:
  - $HOME/.npm

dist: noble

git:
  depth: 1

install:
- npm install --global @choksheak/timecli
- python -m venv .venv
- .venv/bin/python -m pip install --upgrade pip
- timecli ".venv/bin/pip" install --no-cache-dir --requirement requirements.txt
- timecli ".venv/bin/pip" install hello-world --no-cache-dir
- timecli ".venv/bin/pip" uninstall hello-world --no-cache-dir --yes

language: generic

os: linux

script: skip
