env:
  global:
  # [INFO] Equivalent: API_KEY_APPVEYOR = my real key:
  # https://kristinita.netlify.com/Pages/About-for-developers#AppVeyor
  - secure: >
      "qE2c+aZb9QGtPF9VG6WhAP2iT0mTDAnmueEiqWUctgalhAFAJ4wdSqvHNNv+F2178wE92WcpT3/
      chmJltlBj1Qqx6vWevJR2ff1uNbQnwGHYBw+1c8JOvx7mUvisp/nzU1eIpU50/
      uDMF6PnUQ7j269nE1seEjUo7aP98rVHDXZ1uYaOVIEKq40HhLMOlfQg4mhpN1zxQLL7eCy7YgQWXDUb4yRT6TU1BxI3uIC9y8LVgv0le3L8hikD2yR
      ++wJwFHSu9nTm9/
      liSxCb4TINZ/mILZ7nzC4UWfNqwRgzz+5n4klcHxeuDORRh9dFQnN3EGsdrScf0Re1oDdUezdYkvgCRzWIgYYPn0FNnmuZl3ccg6JDhRyV+
      LzTv+XiosDojqdHr7R10ae/
      2gyExR+uARIvf0dFnTIBztVnKRtzuPYdsPOkU7R6rM8FnMAjK4G5yjJO4QcZqMo+BzY8O2gqWFba6nxhDk1OBWj/14+jU2pfkW8cR4vq3Us/
      upPuNJhHdtv+S5vuuF9/
      CksWBqUi3QMQYkSMT5Xkv5YcTeWqQe6W4U2hVg7+Tl1jesn2WP6nM6j
      +I2W5fJwYWIKB7U0hP6WR0jkrHDvMNfWgaB8VZCxYoVUFvCMf5IBnXgRGkYjJn9KkQv3pfODC5aUdep2mCWL+cYiHBukRncS66bs/
      EAE="

install:
- wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
- sudo dpkg -i packages-microsoft-prod.deb
- sudo apt-get install apt-transport-https
- sudo apt-get update
- sudo apt-get install dotnet-sdk-2.2
- dotnet tool install -g localappveyor

script:
- localappveyor --help
