git:
  depth: 1
matrix:
  include:
  - script:
    - mkdir "output/screenshots"
    - touch "output/screenshots/KiraSecondFile.txt"
    - MATRIX_DEPLOY=1
  - script:
    - echo "Kira Goddess!"
deploy:
  provider: pages
  on:
    all_branches: true
    condition: $MATRIX_DEPLOY
  keep-history: true
  skip-cleanup: true
  local-dir: output
  target-branch: master
  repo: Kristinita/SashaTravis.github.io
  github-token: $GITHUB_TOKEN
  verbose: true