# Test
sudo: enabled
dist: xenial
language: python
python: 3.7
mono: none
dotnet: 2.1
git:
  depth: 1
install:
- dotnet tool install -g localappveyor --version 0.5.0-alpha.10
script:
- localappveyor lint --token $APPVEYOR_API_KEY