before_script:
- cat /etc/os-release | grep "VERSION"
- node --version
- npx flow --version
- npx flow-typed --version
- npx shx ls -R flow-typed

cache:
  directories:
  - $HOME/.npm

dist: noble

git:
  depth: 1

install:
- nvm install node
- npm install --save-dev flow-bin flow-typed shx
- npx flow init
- npx flow-typed install

language: shell

os: linux

script:
- npx flow kira-example.js
