build_script:
- pa11y-ci --config .pa11yci.js https://pa11y.org/

cache:
- "%LOCALAPPDATA%\\npm-cache"

clone_depth: 1

image: Visual Studio 2022

install:
- npm install --global pa11y-ci

platform: x64
