build_script:
- npx pa11y --version
- npx pa11y-ci --version
- npx pa11y https://pa11y.org/ --debug
- npx pa11y-ci https://pa11y.org/

cache:
- "%LOCALAPPDATA%\\npm-cache"

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

image: Visual Studio 2022

install:
- npm install

platform: x64
